# Generated by Django 5.1 on 2024-08-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_catagory_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descriptions',
            new_name='description',
        ),
    ]
